### PR TITLE
Resubmit MibS paper

### PR DESCRIPTION
**Pull request by SaTahernejad**

### CODE REVIEW

**Comment by tkralphs** [comment]
I guess you've seen that we're getting a couple of different failures here. Can you check them?

**Comment by SaTahernejad** [comment]
Sure. Let me check it.

**Comment by SaTahernejad** [comment]
Travis could build MibS and also solved the test problem successfully, but I cannot find out why AppVeyor failed. Do you have any ideas?

**Comment by tkralphs** [comment]
Everything seems good now!

**Pull request merged**
