### PR TITLE
Showing help after typing mibs

### PR DESCRIPTION
**Pull request by SaTahernejad**

### CODE REVIEW

**Comment by SaTahernejad** [comment]
It seems that MIBS_VERSION and MIBS_GIT_VERSION are not defined. I am not sure that how I can get them.

**Comment by SaTahernejad** [comment]
I added the introduction into MibSMain.cpp. I think it can also be added to MibSModel.cpp. What is your suggestion?

**Comment by tkralphs** [comment]
Can you move this to `master`? We should only be committing new things like this to master. We can then cherry pick or merge to stable branches.

**Comment by tkralphs** [comment]
By the way, MIBS_VERSION and MIBS_GIT_VERSION should be defined by the configure script at build time in the autoconf header. You can check how this is done in other COIN projects.

**Comment by tkralphs** [comment]
Can you also move this to master?

**Comment by SaTahernejad** [comment]
> Can you also move this to master?

Sure. I will send all of them today.

**Pull request closed without merging**
